name = "teawie-api"
main = "src/index.ts"
compatibility_date = "2023-11-11"

workers_dev = false
send_metrics = false

kv_namespaces = [
	{ binding = "TEAWIE_API", id = "653497aea3b3409299a79fecb35b3405" }
]
