name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Install Dependencies
        run: nix develop .#ci --command pnpm install --frozen-lockfile

      - name: Run build
        run: nix develop .#ci --command nrr build

  treefmt:
    name: Treefmt

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v13

      - name: Run checks
        run: |
          nix develop .#ci --command treefmt --fail-on-change

  release-gate:
    name: CI Release gate
    needs: [build, treefmt]

    if: always()

    runs-on: ubuntu-latest

    steps:
      - name: Exit with error
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
