name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Activate corepack
        run: |
          corepack enable
          corepack prepare --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm build

  format-and-lint:
    name: Format & lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Run checks
        run: |
          nix flake check \
            --print-build-logs \
            --show-trace
