name: deploy

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    permissions:
      security-events: write

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - name: download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: deploy to cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: teawieapi
          directory: dist
          gitHubToken: ${{ github.token }}
