name: ESLint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  eslint:
    name: Run ESLint scan
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        continue-on-error: true
        run: pnpm run lint --format @microsoft/eslint-formatter-sarif --output-file /tmp/results.sarif

      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: /tmp/results.sarif
          wait-for-processing: true
